PREFIX ?=/usr/local
CC = gcc
LD = gcc
CFLAGS = -g -wall -I$(PREFIX)/lua/include
LGFLAGS = -L$(PREFIX)/lua/lib


test:
	@echo "CC = " $(CC)
	@echo "LD = " $(LD)
	@echo "CFLAGS = " $(CFLAGS)
	@echo "LDFLAGS = " $(LDFLAGS)
