#用make命令可以覆盖Makefile中指定的值
 例如:
  //-----------------Makefile-------------------
   LUA_INCLUDE_DIR = /usr/local/include 
   echo:
		@echo "LUA_INCLUDE_DIR=$(LUA_INCLUDE_DIR)"
  //--------------------------------------------
 
 当前文件下输入make,则输出
	LUA_INCLUDE_DIR=/usr/local/include
 如果make后加上参数,如:
	make LUA_INCLUDE_DIR=/abc
 则输出
	LUA_INCLUDE_DIR=/abc
 

